version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./data:/opt/spark/data
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    networks:
      - spark-network

  spark-submit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-submit
    hostname: spark-submit
    depends_on:
      - spark-master
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./requirements.txt:/opt/spark/requirements.txt
    entrypoint: ["/bin/bash", "-c"]
    command: >
      echo "Installing requirements..." &&
      cat /opt/spark/requirements.txt && 
      pip install -r /opt/spark/requirements.txt &&
      /opt/spark/bin/spark-submit --master spark://spark-master:7077 /opt/spark/scripts/run_scripts.py
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
